### ISSUE TITLE
Styling: Suggestion Screen

### ISSUE THREAD

**Issue by adikakade31** [codepath-android-fall16-group-8/travel#103]
- Changing font color, size
- Replacing star with plus and tick on selection(since plus is more intuitive for this app)
- Replacing create button to textview the way its in google trips
- Changing color of loading toolbar from orange to a more pleasant color
Other small UI changes may be there.

**Comment by prav90** [comment]
@adikakade31 Isn't this related to the refactor which I'm doing already for the places suggestion activity?

**Comment by adikakade31** [comment]
There are some UI styling which I had in mind and am working on it.

**Comment by prav90** [comment]
@adikakade31 can you add in the description so that I don't end up doing the same thing?
