### ISSUE TITLE
Parse Server

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#2]

**Comment by adikakade31** [comment]
Added parse server configuration. Please review code in the branch parse-server.
Heroku App: traveltrails(https://traveltrails.herokuapp.com/)
mLab database: https://www.mlab.com/databases/heroku_2mnrdp58

**Comment by heyhuyen** [comment]
I'm not sure what the proper way is to link PRs to issues so I'm just going to link the PR here: https://github.com/codepath-android-fall16-group-8/travel/pull/11.

Let's have assignees close issues after merging PRs (assuming nothing breaks).
