### ISSUE TITLE
Bug: App crashes on click of Story Collage view after taking photos

### ISSUE THREAD

**Issue by adikakade31** [codepath-android-fall16-group-8/travel#23]
Steps to reproduce-
1. Create a new trip with at least one place. 
2. Click camera icon to take photos for that place.
3. Take a photo and go back to app
4. Go to Story Collage view, app crashes.

Exception- 
`FATAL EXCEPTION: main
                                                                     Process: com.codepath.travel, PID: 15776
                                                                     org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.codepath.travel.models.StoryPlace, verify that your class is configured properly and that the Parcelable class com.codepath.travel.models.StoryPlace$$Parcelable is generated by Parceler.`

**Comment by heyhuyen** [comment]
I'm working on this!
