### ISSUE TITLE
Show suggested places for a destination

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#31]
After a user creates a trip and has selected a destination, show the top X places for that destination.

From Readme:
- "Top 10" in categories for that destination (i.e.Categories- Things to Do, Places to Eat, Sights to See)
- Each category can be scrolled horizontally
- Each item within the category has a title and respective image

**Comment by adikakade31** [comment]
Also add -
- Choose an item from category and add to trip
- Navigate to cart view as shown in wireframe

**Comment by adikakade31** [comment]
PR #55

**Comment by adikakade31** [comment]
API Key added in GoogleAsyncHttpClient is for showing suggested places using Places API Web Service
https://developers.google.com/places/web-service/search
