### ISSUE TITLE
Sprint 1 Feedback!

### ISSUE THREAD

**Issue by codepathreview** [codepath-android-fall16-group-8/travel#36]
:+1:  Nice work creating wire-frames and implementing substantial stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:

* Well created detailed stories/tasks on the project wiki.
* Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
* Good job by everyone to [contribute ](https://github.com/codepath-android-fall16-group-8/travel/graphs/contributors)to the project.
* Great work creating milestones. Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all detailed issues into [milestones](https://github.com/codepath-android-fall16-group-8/travel/milestones) representing sprints so that its easier for you to track progress of the project. 
* Good to see that your team created regular commits/pull requests to sync up your code to avoid having multiple conflicts at the end.
* Nice work creating and distributing tasks to create database schema, parse integration and models.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.

**Comment by codepathreview** [comment]
Hello @adikakade31  @heyhuyen  @prav90 

Please also update your `README.md` to include a GIF or video walkthrough [as described here](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-creating-the-project-readme) and then [re-submit your project](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-submitting-through-course-system) through the course system.

**Comment by heyhuyen** [comment]
@codepathreview thanks for the feedback!

I added a link to the video walkthrough to the README and resubmitted through the course system. Let us know if that didn't work.

**Comment by codepathreview** [comment]
Thanks for the update 👍
