### ISSUE TITLE
Enable viewing of other people's shared stories

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#38]
A user should be able to see the shared stories of the user's they are following.

**Comment by heyhuyen** [comment]
This will probably get covered in #61 . In which case we can close this as a "duplicate"

**Comment by prav90** [comment]
#65  covers this. We might not need any additional flag to enable sharing. Parse Objects come with permission flags, we can set the read by everyone flag to true, when the user decides to share it with everyone.
