### ISSUE TITLE
A user can share their story with friends

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#39]

**Comment by heyhuyen** [comment]
Just an idea, to simplify this feature: could add a "shared" flag to the Trip object. This shares the story to anyone following that user.

Extension: be able to share with specific users. Would be nice if the other user then received a notification... but that's a whole other feature in and of itself.

**Comment by prav90** [comment]
@heyhuyen We don't need a shared flag. Check out parse object's ACL permissions. We can set the read by flag for the story object to a specific user or to everyone to share the story. check this link http://parseplatform.github.io/docs/android/guide/#security-for-other-objects

**Comment by heyhuyen** [comment]
@prav90, cool, will do, thanks!
