### ISSUE TITLE
Cleanup Create New Trip flow

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#73]
When the FAB is clicked to create a new trip, directly bring up the google fragment (remove the dialog fragment). Then go directly to the cart view.

**Comment by adikakade31** [comment]
Removed FAB since Google autocomplete fragment included in xml is the one whose onclick pulls up search view and FAB onclick cannot simulate that.
Added Google autocomplete search to the toolbar instead.

Opening a new issue for styling of the search.

**Comment by adikakade31** [comment]
PR #82
