### ISSUE TITLE
Add Coordinator Layout back in

### ISSUE THREAD

**Issue by heyhuyen** [codepath-android-fall16-group-8/travel#78]

**Comment by heyhuyen** [comment]
whoops. didn't see that you picked this up. Just FYI I added the windowTranslucent setting in order to make the nav drawer comply with the material design guide (slide out under translucent status bar), which pushes everything up under the status bar as well. To correct it, we have to set "fitSystemWindows=true" to the root layouts that we want to snap below the status bar. I've fixed it for the home activity and profile activity in a PR i'm about to issue. The other activities will need a similar fix.

**Comment by prav90** [comment]
@heyhuyen No worries. I'm doing it right now for place suggestion and place detail activity. So your changes shouldn't conflict mine

**Comment by heyhuyen** [comment]
Looks like we've done most of this, except for the Search users activity, so I'll add that and then we can close this.
