### ISSUE TITLE
Modify Suggestion screen to have trip image  

### ISSUE THREAD

**Issue by adikakade31** [codepath-android-fall16-group-8/travel#93]
Suggestion screen currently has title but no image of the destination. 
Include cover pic of destination on top of page which gets minimized to just title on scroll similar to Google trips.
Make the screen look better!

**Comment by heyhuyen** [comment]
:+1:

I think the scroll minimizing will require coordinator layout... sounds like it could be pretty tricky. This is applicable to the story screen too.

**Comment by adikakade31** [comment]
yea. Will first add the cover photo and then will work on achieving the scroll and then apply to story screen after its done.
