### ISSUE TITLE
Styling: Story View

### ISSUE THREAD

**Issue by adikakade31** [codepath-android-fall16-group-8/travel#98]

**Comment by heyhuyen** [comment]
@adikakade31, trip item view (issue #96 ) is pretty much the feed.

**Comment by adikakade31** [comment]
Okay, will change it to Story View then.

**Comment by heyhuyen** [comment]
😓 I'm actually working on the story view right now. Maybe we can trade. I'll take this one and you can do the trip item view for all the trip feeds.

**Comment by adikakade31** [comment]
Sure
